version: '3.8'

services:

  # ---------------------------
  # Zookeeper
  # ---------------------------
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # ---------------------------
  # Kafka
  # ---------------------------
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  # ---------------------------
  # Discovery Server (Eureka)
  # ---------------------------
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - kafka

  # ---------------------------
  # NFL Team Service
  # ---------------------------
  nfl-team-service:
    build: ./nfl-team-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  # ---------------------------
  # API Gateway
  # ---------------------------
  nfl-api-gateway:
    build: ./nfl-api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
